spring.application.name=sistemaEstoque

spring.datasource.url=jdbc:postgresql://localhost:5432/wajunkai
spring.datasource.username=postgres
spring.datasource.password=Ghostxis123


spring.flyway.enabled=true
spring.flyway.schemas=public
spring.jpa.properties.hibernate.default_schema=public
spring.flyway.locations=classpath:db/migration

spring.jpa.hibernate.ddl-auto=validate
api.security.token.secret=${JWT_SECRET:minha-chave-padrao-dev-123}

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

