spring.application.name=sistemaEstoque

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/wajunkai}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:Ghostxis123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.schemas=public
spring.flyway.locations=classpath:db/migration

spring.jpa.properties.hibernate.default_schema=public
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.secret=${JWT_SECRET:minha-chave-padrao-dev-123}