spring.application.name=sistemaEstoque
# Conexão com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/wajunkai
spring.datasource.username=postgres
spring.datasource.password=Ghostxis123
spring.datasource.driver-class-name=org.postgresql.Driver

# Garante que o Flyway e o Hibernate usem o mesmo schema (opcional, mas recomendado)
spring.flyway.schemas=public
spring.jpa.properties.hibernate.default_schema=public

# Segurança e Validação
spring.jpa.hibernate.ddl-auto=validate

# Mostra o SQL no console (Essencial para debugar em desenvolvimento)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration